### ISSUE TITLE
Every page and content is 404 Not Found

### ISSUE THREAD

**Issue by myusufid** [dashdashzako/hugo-journal#6]
I don't know why it is every my page & content always 404 
am i missing something?
do you have an example for this theme?

![Screen Shot 2019-09-24 at 11 18 03](https://user-images.githubusercontent.com/17339708/65480810-11c7c200-debd-11e9-8011-d26243495cdb.png)
![Screen Shot 2019-09-24 at 11 18 12](https://user-images.githubusercontent.com/17339708/65480811-12605880-debd-11e9-9dc6-7af9e1ccd35f.png)

my config toml
```
baseURL = 'http://localhost:1313'
title = 'Yusuf Blogs'
theme = 'hugo-journal'

[params]
  description = "Blog meta description."
  githubUsername = "your_gh_username"
  twitterUsername = "your_twitter_handle"
  tagline = "Blog tagline. Shown under index title."
[params.work]
  jobTitle = "occupation"
  company = "the company"
  companyUrl = "https://the.company.url/"
```

**Comment by mbielsk** [comment]
I had the same problem. I've just moved */content/posts/* to */content/post/* and it worked.
